name: auto-version-release

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]


concurrency:
  group: auto-release-group
  cancel-in-progress: true

run-name: ${{ github.actor }}'s close of PR ${{ github.ref_name }} has started the AVR workflow-selector

jobs:
  wf-selector:
    uses: kohirens/version-release/.github/workflows/selector.yml@e327d431f54e299bdcefcec1febc08eb71be02ff
    name: workflow-selector
    secrets:
      github_write_token: ${{ secrets.GH_WRITE_TOKEN }}
    with:
      committer_email: 619281+b01@users.noreply.github.com
      committer_name: Khalifah K Shabazz
